# Generated by Django 4.2.7 on 2025-01-05 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "Name must be greater than 1 character"
                            )
                        ],
                    ),
                ),
                ("breed", models.CharField(max_length=100)),
                ("comments", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
