# Generated by Django 4.2.7 on 2024-12-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="Menus",
        ),
        migrations.RenameField(
            model_name="options",
            old_name="menu",
            new_name="menus",
        ),
    ]
